### PR TITLE
improved the scaling and style of the custom play button

### PR DESCRIPTION
**Pull request by AdriaandeJongh**

### CODE REVIEW

**Comment by AdriaandeJongh** [comment]
regarding the scaling on my device, here's a comparison:
Screenshot 2024-01-09 at 16 05 15
Screenshot 2024-01-09 at 16 04 01

**Comment by poohcom1** [comment]
It ends up looking extra large on my side (not sure if it's due to Windows or my screen).

image

Might need to check the engine code and icon to see how they made it properly scaled.

**Comment by AdriaandeJongh** [comment]
hmm, yeah, dang. not as easy as I thought then!

**Comment by poohcom1** [comment]
@AdriaandeJongh Hey, I think I just found the simplest fix for this xD

Turns out there's a "Scale with editor scale" option in the import settings for textures:
image

I'll publish a new version with the fix, hopefully this will resolve scaling issues for all platforms.

**Comment by AdriaandeJongh** [comment]
I was using the GitHub web interface which doesn't give me all the tools I need to modify this PR to something useful, so I'm going to leave adding these tiny changes to you! Just add the following in plugin.gd:
```
play_button.flat = true
play_button.focus_mode = Control.FOCUS_NONE
```

**Pull request closed without merging**
